spring:
  config:
    location: classpath:/application.yml
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
  # datasource
  datasource:
    # druid配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT x
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat, wall
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      url: jdbc:mysql://localhost:3306/miaosha?serverTimezone=GMT
      username: root
      password: 123456!a

  # redis
  redis:
    host: 49.234.28.27
    port: 6379
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        max-wait: 3000
        min-idle: 10
    timeout: 10000

# cache
pageCache:
  enable: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
