spring:
  config:
    location: classpath:/application.yml
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
  # datasource
  datasource:
    # druid配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT x
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat, wall
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      url: jdbc:mysql://172.19.241.75:3306/miaosha?serverTimezone=GMT&useSSL=false
      username: root
      password: 123456!aB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
    publisher-confirms: true
  # redis
  redis:
    host: 49.234.28.27
    port: 6379
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        max-wait: 3000
        min-idle: 10
    timeout: 10000

# cache
pageCache:
  enable: true



mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*.xml
server:
  port: 8090
